const $ = (s) => document.querySelector(s);
const views = [...document.querySelectorAll('.view')];
const role = $('#role');
let state = { mode: 'loading', employees: [], transactions: [], financials: null };
let selected = localStorage.getItem('friends-role') || 'svetlana';
const euro = (n) => new Intl.NumberFormat('en-IE',{style:'currency',currency:'EUR'}).format(Number(n || 0));
const employee = () => state.employees.find(e => e.id === selected);
const notify = (text, bad=false) => { const n=$('#notice'); n.textContent=text; n.className=bad?'notice-bad':'notice-good'; };
const projectName = (p) => p === 'A' ? 'Respectable Relatives' : 'Drunk University Friends';
async function load(){try{const r=await fetch('/api/dashboard'); if(!r.ok)throw new Error('Could not load records'); state=await r.json(); $('#mode').textContent=state.mode==='live'?'Live records':'Demo preview'; role.innerHTML=state.employees.map(e=>`<option value="${e.id}">${e.name}</option>`).join(''); role.value=selected; render();}catch(e){notify(e.message,true)}}
function can(action){const e=employee();return action==='sale'?e?.role==='salesperson':action==='expense'?e?.role==='expense_reporter':e?.role==='manager'}
function render(){ renderDashboard(); renderEntry(); renderDecisions(); renderRecords(); renderSetup(); $('#queue').textContent=state.transactions.filter(t=>t.status==='pending'||t.status==='awaiting_allocation').length; }
function lines(items){return `<ul class="metric-list">${items.map(([label,value])=>`<li><span>${label}</span><strong>${value}</strong></li>`).join('')}</ul>`}
function renderDashboard(){const f=state.financials;if(!f)return; $('#dashboard').innerHTML=`<div class="cards"><article class="card"><h3>Respectable Relatives</h3><div class="amount">${euro(f.projects.A.result)}</div><p class="sub">Project A result</p></article><article class="card"><h3>Drunk University Friends</h3><div class="amount">${euro(f.projects.B.result)}</div><p class="sub">Project B result</p></article><article class="card"><h3>Company result</h3><div class="amount">${euro(f.company.result)}</div><p class="sub">All approved sales less all expenses</p></article></div><div class="summary"><article class="panel"><h2>Project A</h2>${lines([['Approved income',euro(f.projects.A.income)],['Commission expense',euro(f.projects.A.commissions)],['Allocated expenses',euro(f.projects.A.expenses)],['Result',euro(f.projects.A.result)]])}</article><article class="panel"><h2>Project B</h2>${lines([['Approved income',euro(f.projects.B.income)],['Commission expense',euro(f.projects.B.commissions)],['Allocated expenses',euro(f.projects.B.expenses)],['Result',euro(f.projects.B.result)]])}</article><article class="panel"><h2>Company view</h2>${lines([['Company overhead',euro(f.overhead)],['Awaiting allocation',euro(f.awaiting)],['Richard commission',euro(f.commissionByPerson[0])],['Anastasia commission',euro(f.commissionByPerson[1])],['Jean-Claude commission',euro(f.commissionByPerson[2])],['Company result',euro(f.company.result)]])}</article></div>`}
function renderEntry(){let html='<p class="empty">Choose a salesperson to enter a sale or Kevin to enter an expense.</p>';if(can('sale'))html=$('#sale-form').innerHTML;if(can('expense'))html=$('#expense-form').innerHTML;$('#entry').innerHTML=html;const form=$('#entry form');if(form)form.addEventListener('submit',submitTransaction)}
async function submitTransaction(ev){ev.preventDefault();const f=new FormData(ev.currentTarget), type=ev.currentTarget.dataset.type;let payload;if(type==='sale')payload={customer:f.get('customer'),project:f.get('project').startsWith('A')?'A':'B',description:f.get('description'),amount:Number(f.get('amount')),proposedSplit:['r','a','j'].map(k=>Number(f.get(k)))};else payload={description:f.get('description'),category:f.get('category'),amount:Number(f.get('amount')),proposedAllocation:f.get('allocation')};await post('/api/transactions',{reference:f.get('reference').trim(),type,submittedBy:selected,payload});}
function decisionCard(t){if(t.type==='sale'){const s=t.payload.proposedSplit;return `<article class="panel decision"><div><h3>${t.reference} · ${projectName(t.payload.project)} · ${euro(t.payload.amount)}</h3><p>${t.payload.customer} — ${t.payload.description}</p><p>Proposed split: ${s.join(' / ')}%</p></div><div class="actions"><label>Richard<input value="${s[0]}" type="number" data-split="0"></label><label>Anastasia<input value="${s[1]}" type="number" data-split="1"></label><label>Jean-Claude<input value="${s[2]}" type="number" data-split="2"></label><button data-approve="${t.reference}">Approve sale</button></div></article>`}return `<article class="panel decision"><div><h3>${t.reference} · ${euro(t.payload.amount)}</h3><p>${t.payload.description} — ${t.payload.category}</p><p>Proposed allocation: ${t.payload.proposedAllocation}</p></div><div class="actions"><label>Final allocation<select data-allocation><option ${t.payload.proposedAllocation==='A'?'selected':''} value="A">Project A</option><option ${t.payload.proposedAllocation==='B'?'selected':''} value="B">Project B</option><option ${t.payload.proposedAllocation==='Company overhead'?'selected':''}>Company overhead</option></select></label><button data-approve="${t.reference}">Confirm allocation</button></div></article>`}
function renderDecisions(){if(!can('decision')){$('#decisions').innerHTML='<p class="empty">Only Svetlana can make manager decisions.</p>';return}const q=state.transactions.filter(t=>t.status==='pending'||t.status==='awaiting_allocation');$('#decisions').innerHTML=q.length?q.map(decisionCard).join(''):'<p class="empty">No sales or allocations are waiting for a decision.</p>';document.querySelectorAll('[data-approve]').forEach(b=>b.addEventListener('click',async()=>{const t=state.transactions.find(x=>x.reference===b.dataset.approve), panel=b.closest('.decision');if(t.type==='sale')await post('/api/approve',{actorId:selected,reference:t.reference,approvedSplit:[...panel.querySelectorAll('[data-split]')].map(i=>Number(i.value))});else await post('/api/approve',{actorId:selected,reference:t.reference,finalAllocation:panel.querySelector('[data-allocation]').value})}))}
function renderRecords(){const visible=state.transactions.filter(t=>employee()?.role==='manager'||t.submittedBy===selected);$('#records').innerHTML=`<div class="records">${visible.map(t=>{const detail=t.type==='sale'?`${t.payload.customer} · Project ${t.payload.project} · ${t.payload.description}`:`${t.payload.category} · proposed ${t.payload.proposedAllocation} · ${t.payload.description}`;const sync=t.sheetSyncStatus==='failed'?`<button class="retry" data-retry="sheet" data-ref="${t.reference}">Retry Sheets</button>`:'';const notice=t.notificationStatus==='failed'?`<button class="retry" data-retry="notification" data-ref="${t.reference}">Retry notification</button>`:'';return `<article class="record"><strong class="ref">${t.reference}</strong><div><strong>${euro(t.payload.amount)}</strong><p>${detail}</p><p>Submitted by ${state.employees.find(e=>e.id===t.submittedBy)?.name||t.submittedBy} · Sheets: ${t.sheetSyncStatus||'pending'} · Notification: ${t.notificationStatus||'not required'}</p>${sync}${notice}</div><span class="status ${t.status}">${t.status.replace('_',' ')}</span></article>`}).join('')||'<p class="empty">No records for this role.</p>'}</div>`;document.querySelectorAll('[data-retry]').forEach(b=>b.addEventListener('click',()=>post('/api/retry',{reference:b.dataset.ref,target:b.dataset.retry}))) }
function renderSetup(){if(!can('decision')){$('#setup').innerHTML='<p class="empty">Only Svetlana can link a Telegram account.</p>';return}$('#setup').innerHTML=`<article class="panel"><h2>Manager setup</h2><p class="setup-note">Link a Telegram user ID to one fictional employee. This does not change old records or their notification chat.</p><form class="form" id="link-form"><div class="form-grid"><label>Employee<select name="employeeId">${state.employees.filter(e=>e.id!=='svetlana').map(e=>`<option value="${e.id}">${e.name}</option>`).join('')}</select></label><label>Telegram user ID<input name="telegramUserId" required></label><label>Telegram chat ID<input name="telegramChatId" required></label></div><button>Save link</button></form></article>`;$('#link-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);post('/api/manager-setup',{actorId:selected,employeeId:f.get('employeeId'),telegramUserId:f.get('telegramUserId'),telegramChatId:f.get('telegramChatId')})})}
async function post(url,body){try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),data=await r.json();if(!r.ok)throw new Error(data.error||'That action could not be completed.');notify(data.confirmation||'Saved successfully.');await load()}catch(e){notify(e.message,true)}}
role.addEventListener('change',()=>{selected=role.value;localStorage.setItem('friends-role',selected);render()});document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t===tab));views.forEach(v=>v.classList.toggle('active',v.id===tab.dataset.view))}));$('#seed').addEventListener('click',()=>notify(state.mode==='demo'?'The completed Test 1 + Test 2 records are already showing in demo preview. Connect Supabase to persist them.':'Use the supplied references only once; the live database currently shows its saved records.'));load();
